// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_feed_link.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addUserFeedLink = `-- name: AddUserFeedLink :one
INSERT INTO user_feed_link (user_id, feed_id, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING user_id, feed_id, created_at, updated_at
`

type AddUserFeedLinkParams struct {
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) AddUserFeedLink(ctx context.Context, arg AddUserFeedLinkParams) (UserFeedLink, error) {
	row := q.db.QueryRowContext(ctx, addUserFeedLink,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserFeedLink
	err := row.Scan(
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFeedFollows = `-- name: GetUserFeedFollows :many
SELECT ufl.feed_id, ufl.created_at , f.title, f.url
FROM user_feed_link ufl
LEFT JOIN feeds f ON ufl.feed_id = f.id
WHERE ufl.user_id = $1
`

type GetUserFeedFollowsRow struct {
	FeedID    uuid.UUID
	CreatedAt time.Time
	Title     sql.NullString
	Url       sql.NullString
}

func (q *Queries) GetUserFeedFollows(ctx context.Context, userID uuid.UUID) ([]GetUserFeedFollowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeedFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedFollowsRow
	for rows.Next() {
		var i GetUserFeedFollowsRow
		if err := rows.Scan(
			&i.FeedID,
			&i.CreatedAt,
			&i.Title,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
