// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_feed_link.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserFeedLink = `-- name: AddUserFeedLink :one
INSERT INTO user_feed_link (user_id, feed_id, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING user_id, feed_id, created_at, updated_at
`

type AddUserFeedLinkParams struct {
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) AddUserFeedLink(ctx context.Context, arg AddUserFeedLinkParams) (UserFeedLink, error) {
	row := q.db.QueryRowContext(ctx, addUserFeedLink,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserFeedLink
	err := row.Scan(
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
